from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Dict, Any, Optional, List


@dataclass
class ToolCall:
    """Represents a tool execution request generated by the model."""
    id: str
    tool_name: str
    arguments: Dict[str, Any]


@dataclass
class LLMMessage:
    """Normalized message representation across providers."""
    role: str  # "system", "user", "assistant", "tool"
    content: Optional[str] = None
    tool_call_id: Optional[str] = None
    tool_calls: Optional[List[ToolCall]] = None


@dataclass
class LLMResponse:
    """Normalized output returned by an LLM call."""
    content: Optional[str] = None
    tool_calls: List[ToolCall] = field(default_factory=list)
    finish_reason: str = "stop"  # "stop", "tool_calls", "length"
    total_tokens: int = 0


class BaseLLMClient(ABC):
    """Abstract interface that all LLM client implementations must implement."""

    @abstractmethod
    async def generate(
        self,
        messages: List[LLMMessage],
        tools: Optional[List[Dict[str, Any]]] = None,
        temperature: float = 0.0,
    ) -> LLMResponse:
        pass