services:
  db:
    image: postgres:17
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cortexops
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./app/init_scripts:/docker-entrypoint-initdb.d
  nats:
    image: nats:latest
    container_name: nats_main
    restart: always
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - nats_storage:/data
    command: [ "-js", "-sd", "/data" ]

  cache:
    image: redis:7.2-alpine
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
       - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  pgdata:
  nats_storage:
  redis_data: