services:
  db:
    image: postgres:17
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cortexops
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./app/init_scripts:/docker-entrypoint-initdb.d
  nats:
    image: nats:latest
    container_name: nats_main
    restart: always
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - nats_storage:/data
    command: [ "-js", "-sd", "/data" ]

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db/keycloak
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: adminpassword
    command: start-dev

  cache:
    image: redis:7.2-alpine
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
       - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

  api:
    build: .
    depends_on:
      - db
      - keycloak
volumes:
  pgdata:
  nats_storage:
  redis_data:

