version: '3.8'

services:
  identity:
    build:
      context: ../../
      dockerfile: infrastructure/docker/Dockerfile
    container_name: cortexops_identity
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/cortexops
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_REALM=CortexOps
      - KEYCLOAK_CLIENT_ID=identity-service
      - KEYCLOAK_CLIENT_SECRET=keycloak_client_secret
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASSWORD=adminpassword
      - NATS_URL=nats://nats:4222
    networks:
      - cortexops_network


networks:
  cortexops_network:
    external: true
    name: cortexops_shared_network