services:
  db:
    image: postgres:17
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cortexops
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ../../scripts:/docker-entrypoint-initdb.d
    networks:
      - shared_network
  nats:
    image: nats:latest
    container_name: nats_main
    restart: always
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - nats_storage:/data
    command: [ "-js", "-sd", "/data" ]
    networks:
      - shared_network

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres_db:5432/identity
      KC_DB_USERNAME: user
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: adminpassword
      KC_HOSTNAME: http://localhost:8080
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HTTP_ENABLED: "true"
    command: start-dev
    ports:
      - "8080:8080"
    networks:
      - shared_network

  cache:
    image: redis:7.2-alpine
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
       - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - shared_network

  api:
    build:
      context: ../../
      dockerfile: infrastructure/docker/Dockerfile
    depends_on:
      - db
      - keycloak
    networks:
      - shared_network
volumes:
  pgdata:
  nats_storage:
  redis_data:

networks:
  shared_network:
    name: cortexops_shared_network
    external: true